### ISSUE TITLE
Error with theme switcher

### ISSUE THREAD

**Issue by dsebastien** [dsebastien/website-dsebastien#28]
```
webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:67 Warning: Prop `d` did not match. Server: "M283.211 512c78.962 0 151.079-35.925 198.857-94.792 7.068-8.708-.639-21.43-11.562-19.35-124.203 23.654-238.262-71.576-238.262-196.954 0-72.222 38.662-138.635 101.498-174.394 9.686-5.512 7.25-20.197-3.756-22.23A258.156 258.156 0 0 0 283.211 0c-141.309 0-256 114.511-256 256 0 141.309 114.511 256 256 256z" Client: "M256 160c-52.9 0-96 43.1-96 96s43.1 96 96 96 96-43.1 96-96-43.1-96-96-96zm246.4 80.5l-94.7-47.3 33.5-100.4c4.5-13.6-8.4-26.5-21.9-21.9l-100.4 33.5-47.4-94.8c-6.4-12.8-24.6-12.8-31 0l-47.3 94.7L92.7 70.8c-13.6-4.5-26.5 8.4-21.9 21.9l33.5 100.4-94.7 47.4c-12.8 6.4-12.8 24.6 0 31l94.7 47.3-33.5 100.5c-4.5 13.6 8.4 26.5 21.9 21.9l100.4-33.5 47.3 94.7c6.4 12.8 24.6 12.8 31 0l47.3-94.7 100.4 33.5c13.6 4.5 26.5-8.4 21.9-21.9l-33.5-100.4 94.7-47.3c13-6.5 13-24.7.2-31.1zm-155.9 106c-49.9 49.9-131.1 49.9-181 0-49.9-49.9-49.9-131.1 0-181 49.9-49.9 131.1-49.9 181 0 49.9 49.9 49.9 131.1 0 181z"
    at path
    at svg
    at IconBase
    at FaSun
    at button
    at ThemeSwitcher (webpack-internal:///./client/components/theme-switcher.tsx:27:79)
    at div
    at layout___StyledDiv (webpack-internal:///../../node_modules/styled-components/dist/styled-components.browser.esm.js:28:19542)
    at header
    at layout___StyledHeader (webpack-internal:///../../node_modules/styled-components/dist/styled-components.browser.esm.js:28:19542)
    at div
    at layout___StyledStyledPage (webpack-internal:///../../node_modules/styled-components/dist/styled-components.browser.esm.js:28:19542)
    at Layout (webpack-internal:///./layouts/layout.tsx:324:23)
    at AboutPage
    at MDXProvider (webpack-internal:///../../node_modules/@mdx-js/react/dist/esm.js:138:46)
    at d (webpack-internal:///../../node_modules/next-themes/dist/index.modern.js:8:206)
    at App (webpack-internal:///./pages/_app.tsx:77:24)
    at ErrorBoundary (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:151:5)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:642:24)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:771:24
```

**Comment by dsebastien** [comment]
Caused because of difference between server-side and client-side; one probably considers that theme is X while the other considers that theme is Y.

https://stackoverflow.com/questions/55271855/react-material-ui-ssr-warning-prop-d-did-not-match-server-m-0-0-h-24-v-2
